// Sunvale translations: JA KO TH VI ID (part 4/6) — core UI + items + crops + NPC/mail essentials.
I18N_ADD('ja', {
'title': 'サンベール', 'subtitle': 'のどかなドット農場', 'start': '農場をはじめる', 'continue': 'つづきから', 'new': 'あたらしい農場',
'controls1': 'WASD いどう   E そうさ   SPACE どうぐ', 'controls2': 'I もちもの   H ヘルプ   M おんがく   ESC ポーズ', 'fanmade': 'のどかな農場ゲーム',
'language': '言語', 'day': '日', 'mail': '郵便', 'empty_hands': 'てぶら', 'enter': 'はいる', 'leave': 'でる', 'sleep': 'ねる',
'watch_tv': 'テレビをみる', 'open_chest': 'はこをあける', 'read': 'よむ', 'check_mail': '郵便をみる', 'shop': 'みせ', 'pet_chicken': 'ニワトリをなでる',
'talk_to': '{x}とはなす', 'harvest': '{x}をしゅうかく', 'harvest_generic': 'しゅうかく', 'check_mail_new': '郵便をみる(新{x})',
'sells_for': 'うりね{x}G   {y}', 'costs': 'かかく{x}G   {y}', 'energy_food': '+{x}元気   {y}',
'close': 'とじる', 'inventory': 'もちもの', 'inventory_chest': 'もちもの+はこ', 'chest': 'はこ',
'general_store': 'ざっか店', 'shop_quote': 'ジュニパー:“えらんでね。”', 'buy': 'かう', 'sell': 'うる',
'nothing_sell': 'うるものはない。', 'sell_everything': 'ぜんぶうる', 'close_esc': 'とじる [ESC]',
'mailbox': 'ポスト', 'unread': '未読{x}', 'caught_up': 'ぜんぶよんだ', 'no_mail': '郵便はない。',
'letters_arrive': '手紙がとどく', 'each_morning': 'まいあさ。', 'letters': '手紙{x}つう', 'mailbox_empty': 'ポストはから。',
'village_requests': '村のたのみごと', 'arrive_sleep': 'ねたあとにとどく。', 'from': '{x}より   {y}日',
'request_from': '{x}のたのみ', 'have': '{y}中{x}あり', 'reward': 'ほうび{x}G', 'delivered': 'とどけた',
'need_more': 'たりない', 'deliver': 'とどける', 'enclosed_with': '{x}より', 'taken': 'うけとりずみ', 'claim': 'うけとる',
'nothing_enclosed': '- なし -', 'delete': 'すてる', 'enter_claims': 'ENTERでうけとり/とどける',
'paused': 'ポーズ', 'resume': 'つづける', 'save_game': 'セーブ', 'how_to_play': 'あそびかた',
'music_on': 'おんがく:ON', 'music_off': 'おんがく:OFF', 'quit_title': 'タイトルへ', 'progress_sleep': 'ねるとセーブ',
'sunny': 'はれ', 'rain': 'あめ', 'storm': 'あらし', 'mon': '月', 'tue': '火', 'wed': '水', 'thu': '木', 'fri': '金', 'sat': '土', 'sun': '日',
'best_friends': 'しんゆう', 'friendship': 'なかよし', 'f_full': 'なかよし',
'help.0': 'いどう      WASD / やじるし', 'help.1': 'どうぐ      SPACE / クリック', 'help.2': 'そうさ      E', 'help.3': 'プレゼント  G',
'help.4': 'ダッシュ    SHIFT', 'help.5': 'バー        1-0', 'help.6': 'もちもの    I / TAB', 'help.7': 'にっき      J',
'help.8': '郵便        ポスト', 'help.9': 'ミュート    M', 'help.10': 'ポーズ     ESC', 'help.11': 'とじる     ESC',
'tip.0': '畑のくさにくわをつかう,', 'tip.1': 'たねをまき,毎日みずやり。', 'tip.2': 'ベッドでねてつぎのひへ。',
'tip.3': 'みせでさくもつをうる。', 'tip.4': 'たべると元気かいふく。',
'item.hoe.name': 'くわ', 'item.hoe.desc': '土をたがやす', 'item.can.name': 'じょうろ', 'item.can.desc': '土にみずやり',
'item.axe.name': 'おの', 'item.axe.desc': '木をきる', 'item.pick.name': 'つるはし', 'item.pick.desc': '岩をくだく',
'item.turnip_seeds.name': 'カブのたね', 'item.turnip_seeds.desc': '4日でそだつ',
'item.carrot_seeds.name': 'ニンジンのたね', 'item.carrot_seeds.desc': '5日でそだつ',
'item.potato_seeds.name': 'ジャガイモのたね', 'item.potato_seeds.desc': '6日でそだつ',
'item.tomato_seeds.name': 'トマトのたね', 'item.tomato_seeds.desc': '5日でそだつ',
'item.corn_seeds.name': 'トウモロコシのたね', 'item.corn_seeds.desc': '6日でそだつ',
'item.strawberry_seeds.name': 'イチゴのたね', 'item.strawberry_seeds.desc': '7日でそだつ',
'item.pumpkin_seeds.name': 'カボチャのたね', 'item.pumpkin_seeds.desc': '9日でそだつ',
'item.turnip.name': 'カブ', 'item.turnip.desc': 'シャキッとピリ辛', 'item.carrot.name': 'ニンジン', 'item.carrot.desc': 'あまいシャキシャキ',
'item.potato.name': 'ジャガイモ', 'item.potato.desc': 'ほくほくいも', 'item.tomato.name': 'トマト', 'item.tomato.desc': 'ジューシー',
'item.corn.name': 'トウモロコシ', 'item.corn.desc': '金色の実', 'item.strawberry.name': 'イチゴ', 'item.strawberry.desc': '太陽のベリー',
'item.pumpkin.name': 'カボチャ', 'item.pumpkin.desc': '巨大なカボチャ',
'item.veg_stew.name': '野菜シチュー', 'item.veg_stew.desc': '煮こみ根菜',
'item.omelette.name': 'ハーブオムレツ', 'item.omelette.desc': '新鮮な卵',
'item.berry_pie.name': 'ベリーパイ', 'item.berry_pie.desc': '黄金の皮',
'item.pumpkin_soup.name': 'カボチャスープ', 'item.pumpkin_soup.desc': 'なめらか甘い',
'item.wood.name': '木材', 'item.wood.desc': 'けんちくざいりょう', 'item.stone.name': '石', 'item.stone.desc': 'けんちくざいりょう',
'item.gem.name': 'アメジスト', 'item.gem.desc': '光できらめく', 'item.berry.name': '野生ベリー', 'item.berry.desc': '茂みから',
'item.egg.name': '卵', 'item.egg.desc': '小屋の新鮮卵', 'item.chicken.name': 'ニワトリ', 'item.chicken.desc': 'なかよしな鳥',
'crop.turnip': 'カブ', 'crop.carrot': 'ニンジン', 'crop.potato': 'ジャガイモ', 'crop.strawberry': 'イチゴ', 'crop.pumpkin': 'カボチャ', 'crop.corn': 'トウモロコシ', 'crop.tomato': 'トマト',
'recipe.veg_stew': '根菜を弱火で煮る', 'recipe.omelette': '卵2個とハーブ',
'recipe.berry_pie': '甘い,皮に注意', 'recipe.pumpkin_soup': '谷じゅうぶん',
'upgrade.bag': '大きいリュック', 'upgrade.bag.d': '30→50マス', 'upgrade.chest': 'オークの箱', 'upgrade.chest.d': '箱2倍',
'upgrade.tools': '鋼の道具', 'upgrade.tools.d': '毎回-1',
'npc.mira': 'ミラ', 'npc.bram': 'ブラム', 'npc.juniper': 'ジュニパー', 'npc.pip': 'ピップ', 'npc.wren': 'レン', 'npc.sable': 'セーブル', 'npc.peony': 'ピオニー村長', 'npc.odin': 'オーディン',
'npc.mira.0': "土は水が大好き。作物がのむよ!", 'npc.mira.1': "何も売らないけど農場が大好き。", 'npc.mira.2': "雨は無料の助っ人。空を見て!", 'npc.mira.3': "カボチャは遅いけど高く売れる。",
'npc.bram.0': "岩にアメジスト。つるはしを持って!", 'npc.bram.1': "池で昼寝。いい枕だ。", 'npc.bram.2': "切株を残して。また生える。", 'npc.bram.3': "砂の先の深水に注意。",
'npc.juniper.0': "いらっしゃい!種は棚に,卵はポケットに。", 'npc.juniper.1': "安く買い高く育てる。それが秘訣。", 'npc.juniper.2': "見てても見なくても卵を産むよ。",
'mail.tip0.from': 'ミラ', 'mail.tip0.sub': '水やりの知恵', 'mail.tip0.body': "農夫へ,夜土が湿れば|作物はよく飲む。|雨も有効:空を見て!",
'mail.tip1.from': 'ブラム', 'mail.tip1.sub': '岩と宝', 'mail.tip1.body': "池の砂先の白岩に|アメジスト。|つるはしと元気を。",
'mail.tip2.from': 'ジュニパー', 'mail.tip2.sub': '市の日', 'mail.tip2.body': "店は育てた掘った物|全部高値。|毎日種補充。",
'mail.tip3.from': 'サンベール郵便', 'mail.tip3.sub': '村チラシ', 'mail.tip3.body': "ニワトリは夜卵を産む。|仲良しになでて。|小屋は6羽まで。",
'mail.tip4.from': 'ミラ', 'mail.tip4.sub': 'カボチャ季節', 'mail.tip4.body': "カボチャは9日かかるが|巨大な値段。|早植え忘れる。",
'mail.tip5.from': 'ブラム', 'mail.tip5.sub': '切株', 'mail.tip5.body': "切株が残る。|数日で芽吹き,|森は戻る。",
'mail.tip6.from': 'ジュニパー', 'mail.tip6.sub': '満腹', 'mail.tip6.body': "食べると元気回復。|ベリーを持ち歩き|夕方倒れない。",
'mail.tip7.from': 'サンベール郵便', 'mail.tip7.sub': '天気暦', 'mail.tip7.body': "嵐は一度に全部湿らす。|晴れは土を乾かす。|予報で水やり。",
'mail.tip8.from': 'ブラム', 'mail.tip8.sub': '贈り物', 'mail.tip8.body': "物を持ち村人そばでG|作物は心をつかむ!|大好きが一番!",
'mail.tip9.from': 'ミラ', 'mail.tip9.sub': 'ポストについて', 'mail.tip9.body': "村の頼みは毎朝|ここに届く。頼みを届け|金は君のもの。",
'mail.req0.from': 'ミラ', 'mail.req0.sub': '小さなお願い', 'mail.req0.body': "カブ3個くれる?|ブラムにシチュー作り。|よく払うよ。",
'mail.req1.from': 'ブラム', 'mail.req1.sub': '柵修理', 'mail.req1.body': "池の柵が倒れた。|木8個送って直す。",
'mail.req2.from': 'ジュニパー', 'mail.req2.sub': '焼き注文', 'mail.req2.body': "新鮮卵4個あれば。|朝は焼きが必要|金が待つ。",
'mail.req3.from': 'ミラ', 'mail.req3.sub': 'ジャム', 'mail.req3.body': "野生ベリー5個ぜひ。|冬にジャム作り|金と交換。",
'mail.req4.from': 'ブラム', 'mail.req4.sub': '道', 'mail.req4.body': "村道の修理。|石8個送って村|感謝。",
'mail.req5.from': 'ジュニパー', 'mail.req5.sub': 'スープ', 'mail.req5.body': "今週ニンジンスープ。|君の4個で|利益は君の。",
'mail.req6.from': 'ミラ', 'mail.req6.sub': 'ピクニック', 'mail.req6.body': "熟イチゴ3個ぜひ。|池でピクニック|高値で払う。",
'mail.req7.sub': '宝石', 'mail.req7.body': "アメジスト1個で旅商人と|取引。送って友よ!",
'gift.0': 'ありがとう!ほしかったの。', 'gift.1': '気がきくね!', 'gift.2': 'やさしい心だね。', 'gift.3': '大切にするね。ありがとう!',
'mail.ms0.sub': 'ちょっとしたもの', 'mail.ms0.body': "最近やさしいね,|種をとったよ。|植えて思い出して!",
'mail.ms1.sub': 'ありがとう', 'mail.ms1.body': "村からお礼。|ニンジン甘く早い。|全部売らないで。",
'mail.ms2.sub': '友へ', 'mail.ms2.body': "めったに言わない:|サンベールの良友だよ。|この種をどうぞ。",
'mail.ms3.sub': '心から', 'mail.ms3.body': "もう家族だよ。|村は君の農場の|噂でもちきり。一番いいのを。",
'mail.welcome.sub': 'サンベールへようこそ', 'mail.welcome.body': "農場へようこそ!|ポストは毎朝村の|手紙を集める。小さな|贈り物で開始。",
'mail.week.sub': '最初の週', 'mail.week.body': "村は君を知った。|頼みを届け金と友情を。|隣人と話そう。",
'msg.welcome_farm': 'サンベール農場へようこそ', 'msg.press_h': 'Hでヘルプ', 'msg.welcome_back': 'おかえり',
'msg.new_mail': '新着郵便', 'msg.save_failed': 'セーブ失敗', 'msg.inv_full': 'もちもの一杯',
'msg.rain_waters': '雨が畑をうるおす', 'msg.passed_out': '疲れて倒れた', 'msg.eggs_spoiled': '卵だめ-一杯',
'msg.laid': 'ニワトリが{x}個産んだ', 'msg.not_enough_gold': '金が足りない', 'msg.coop_full': '小屋一杯',
'msg.chicken_joins': 'ニワトリ仲間入り!', 'msg.sold_all': '全部{x}Gで売れた', 'msg.game_saved': 'セーブした',
'msg.too_tired': 'つかれた...', 'msg.not_here': 'ここじゃない', 'msg.dry_ground': 'かわいた土', 'msg.till_first': 'まずたがやす',
'msg.need': '{x} {y}がいる', 'msg.delivered': '配達! +{x}G', 'msg.cluck': 'コケ', 'msg.cluck_bang': 'コケ!',
'msg.no_one': '近くに誰もいない', 'msg.hold_gift': '贈り物を持って', 'msg.not_gift': '贈り物じゃない',
'msg.sound_muted': 'ミュート', 'msg.sound_on': '音あり', 'msg.talked': '+2 なかよし',
'msg.closer': '{x}ともっと仲良し', 'msg.day_weather': '{x}日目 - {y}',
'tv.0': '明日の天気...', 'tv.1': '{x}の予想。計画して!', 'tv.2': '番組に戻ります。',
'sign.farm': 'サンベール農場へようこそ', 'sign.shop': '店 - 種と補給',
'map.farm': 'サンベール農場', 'map.house': '君の家', 'map.shop': 'ざっか店', 'map.hall': '村役場', 'map.tavern': '酒場',
'gift.line': '素敵な贈り物!ありがとう農夫さん。', 'journal': 'にっき',
'tile.0': 'くさ', 'tile.1': 'くさ', 'tile.2': 'はな', 'tile.3': 'みち', 'tile.4': 'みず', 'tile.5': 'つち', 'tile.6': 'ぬれた土',
'tile.7': 'ゆか', 'tile.8': 'かべ', 'tile.9': 'じゅうたん', 'tile.10': 'いし', 'tile.11': 'テラス', 'tile.12': 'はし', 'tile.13': 'すな', 'tile.14': 'さく', 'tile.15': 'かたい木'
});
I18N_ADD('ko', {
'title': '썬베일', 'subtitle': '아늑한 픽셀 농장', 'start': '농장 시작', 'continue': '이어하기', 'new': '새 농장',
'controls1': 'WASD 이동   E 상호작용   SPACE 도구', 'controls2': 'I 인벤토리   H 도움말   M 음악   ESC 일시정지', 'fanmade': '아늑한 농장 게임',
'language': '언어', 'day': '일', 'mail': '우편', 'empty_hands': '빈손', 'enter': '들어가기', 'leave': '나가기', 'sleep': '자기',
'watch_tv': 'TV 보기', 'open_chest': '상자 열기', 'read': '읽기', 'check_mail': '우편 확인', 'shop': '상점', 'pet_chicken': '닭 쓰다듬기',
'talk_to': '{x}와 대화', 'harvest': '{x} 수확', 'harvest_generic': '수확', 'check_mail_new': '우편 확인(새 {x})',
'sells_for': '{x}G에 판매   {y}', 'costs': '{x}G   {y}', 'energy_food': '+{x} 에너지   {y}',
'close': '닫기', 'inventory': '인벤토리', 'inventory_chest': '인벤토리+상자', 'chest': '상자',
'general_store': '잡화점', 'shop_quote': '주니퍼:“골라봐.”', 'buy': '구매', 'sell': '판매',
'nothing_sell': '팔 것 없음.', 'sell_everything': '전부 판매', 'close_esc': '닫기 [ESC]',
'mailbox': '우편함', 'unread': '안 읽음 {x}', 'caught_up': '다 읽음', 'no_mail': '우편 없음.',
'letters_arrive': '편지 도착', 'each_morning': '매일 아침.', 'letters': '편지 {x}통', 'mailbox_empty': '우편함 비었음.',
'village_requests': '마을 부탁', 'arrive_sleep': '잠 후 도착.', 'from': '{x}   {y}일',
'request_from': '{x}의 부탁', 'have': '{y} 중 {x} 보유', 'reward': '보상 {x}G', 'delivered': '배달됨',
'need_more': '더 필요', 'deliver': '배달', 'enclosed_with': '{x} 동봉', 'taken': '받음', 'claim': '받기',
'nothing_enclosed': '- 없음 -', 'delete': '삭제', 'enter_claims': 'ENTER 받기/배달',
'paused': '일시정지', 'resume': '계속', 'save_game': '저장', 'how_to_play': '방법',
'music_on': '음악:켬', 'music_off': '음악:끔', 'quit_title': '타이틀로', 'progress_sleep': '잘 때 저장',
'sunny': '맑음', 'rain': '비', 'storm': '폭풍', 'mon': '월', 'tue': '화', 'wed': '수', 'thu': '목', 'fri': '금', 'sat': '토', 'sun': '일',
'best_friends': '절친', 'friendship': '우정', 'f_full': '우정',
'help.0': '이동        WASD / 방향', 'help.1': '도구        SPACE / 클릭', 'help.2': '상호작용    E', 'help.3': '선물        G',
'help.4': '달리기      SHIFT', 'help.5': '바          1-0', 'help.6': '인벤토리    I / TAB', 'help.7': '일지        J',
'help.8': '우편        우편함', 'help.9': '음소거      M', 'help.10': '일시정지   ESC', 'help.11': '닫기       ESC',
'tip.0': '밭 풀에 괭이 사용,', 'tip.1': '씨앗 심고 매일 물주기.', 'tip.2': '침대에서 자고 다음 날.',
'tip.3': '상점에 작물 판매.', 'tip.4': '먹으면 에너지 회복.',
'item.hoe.name': '괭이', 'item.hoe.desc': '심기 위해 밭갈이', 'item.can.name': '물뿌리개', 'item.can.desc': '땅에 물주기',
'item.axe.name': '도끼', 'item.axe.desc': '나무 베기', 'item.pick.name': '곡괭이', 'item.pick.desc': '바위 깨기',
'item.turnip_seeds.name': '순무 씨앗', 'item.turnip_seeds.desc': '4일 성장',
'item.carrot_seeds.name': '당근 씨앗', 'item.carrot_seeds.desc': '5일 성장',
'item.potato_seeds.name': '감자 씨앗', 'item.potato_seeds.desc': '6일 성장',
'item.tomato_seeds.name': '토마토 씨앗', 'item.tomato_seeds.desc': '5일 성장',
'item.corn_seeds.name': '옥수수 씨앗', 'item.corn_seeds.desc': '6일 성장',
'item.strawberry_seeds.name': '딸기 씨앗', 'item.strawberry_seeds.desc': '7일 성장',
'item.pumpkin_seeds.name': '호박 씨앗', 'item.pumpkin_seeds.desc': '9일 성장',
'item.turnip.name': '순무', 'item.turnip.desc': '아삭 매콤', 'item.carrot.name': '당근', 'item.carrot.desc': '달콤 아삭',
'item.potato.name': '감자', 'item.potato.desc': '든든한 덩이', 'item.tomato.name': '토마토', 'item.tomato.desc': '즙 많고 따뜻',
'item.corn.name': '옥수수', 'item.corn.desc': '황금 이삭', 'item.strawberry.name': '딸기', 'item.strawberry.desc': '햇살 베리',
'item.pumpkin.name': '호박', 'item.pumpkin.desc': '거대한 호박',
'item.veg_stew.name': '야채 스튜', 'item.veg_stew.desc': ' 푹 끓인 뿌리',
'item.omelette.name': '허브 오믈렛', 'item.omelette.desc': '신선한 달걀',
'item.berry_pie.name': '베리 파이', 'item.berry_pie.desc': '황금 껍질',
'item.pumpkin_soup.name': '호박 수프', 'item.pumpkin_soup.desc': '부드럽고 달콤',
'item.wood.name': '목재', 'item.wood.desc': '건축 자재', 'item.stone.name': '돌', 'item.stone.desc': '건축 자재',
'item.gem.name': '자수정', 'item.gem.desc': '빛에 반짝', 'item.berry.name': '야생 베리', 'item.berry.desc': '덤불에서',
'item.egg.name': '달걀', 'item.egg.desc': '신선한 달걀', 'item.chicken.name': '닭', 'item.chicken.desc': '친근한 새',
'crop.turnip': '순무', 'crop.carrot': '당근', 'crop.potato': '감자', 'crop.strawberry': '딸기', 'crop.pumpkin': '호박', 'crop.corn': '옥수수', 'crop.tomato': '토마토',
'recipe.veg_stew': '뿌리를 약불에 끓이기', 'recipe.omelette': '달걀2와 허브',
'recipe.berry_pie': '달콤, 껍질 주의', 'recipe.pumpkin_soup': '골짜기 충분',
'upgrade.bag': '큰 가방', 'upgrade.bag.d': '30→50칸', 'upgrade.chest': '참나무 상자', 'upgrade.chest.d': '상자 2배',
'upgrade.tools': '강철 도구', 'upgrade.tools.d': '매번 -1',
'npc.mira': '미라', 'npc.bram': '브램', 'npc.juniper': '주니퍼', 'npc.pip': '핍', 'npc.wren': '렌', 'npc.sable': '세이블', 'npc.peony': '피오니 촌장', 'npc.odin': '오딘',
'npc.mira.0': "흙은 물을 좋아해. 작물이 마셔!", 'npc.mira.1': "파는 건 없지만 농장이 좋아.", 'npc.mira.2': "비는 무료 도우미. 하늘 봐!", 'npc.mira.3': "호박은 느리지만 값이 좋아.",
'npc.bram.0': "바위에 자수정. 곡괭이 가져와!", 'npc.bram.1': "연못에서 낮잠. 좋은 베개.", 'npc.bram.2': "그루터기 남겨. 다시 자라.", 'npc.bram.3': "모래 뒤 깊은 물 조심.",
'npc.juniper.0': "어서와! 씨앗은 선반, 달걀은 주머니.", 'npc.juniper.1': "싸게 사서 높게 키워. 그게 비결.", 'npc.juniper.2': "봐도 안 봐도 알을 낳아.",
'mail.tip0.from': '미라', 'mail.tip0.sub': '물주기 지혜', 'mail.tip0.body': "농부에게, 밤 흙이 젖으면|작물이 잘 마셔.|비도 유효: 하늘 봐!",
'mail.tip1.from': '브램', 'mail.tip1.sub': '바위와 보물', 'mail.tip1.body': "연못 모래 뒤 흰 바위에|자수정.|곡괭이와 에너지.",
'mail.tip2.from': '주니퍼', 'mail.tip2.sub': '장날', 'mail.tip2.body': "상점은 키운 캔 것 전부|제값. |매일 씨앗.",
'mail.tip3.from': '썬베일 우편', 'mail.tip3.sub': '마을 전단', 'mail.tip3.body': "닭은 밤에 알을 낳아.|우정 위해 쓰다듬어.|우리 6마리까지.",
'mail.tip4.from': '미라', 'mail.tip4.sub': '호박철', 'mail.tip4.body': "호박은 9일 걸리지만|거대한 값.|일찍 심고 잊어.",
'mail.tip5.from': '브램', 'mail.tip5.sub': '그루터기', 'mail.tip5.body': "그루터기가 남아.|며칠에 싹,|숲은 돌아와.",
'mail.tip6.from': '주니퍼', 'mail.tip6.sub': '든든함', 'mail.tip6.body': "먹으면 에너지 회복.|베리 휴대|저녁에 쓰러지지 않아.",
'mail.tip7.from': '썬베일 우편', 'mail.tip7.sub': '날씨 달력', 'mail.tip7.body': "폭풍은 한 번에 흠뻑.|맑음은 흙 말림.|예보 보고 물주기.",
'mail.tip8.from': '브램', 'mail.tip8.sub': '선물', 'mail.tip8.body': "물건 들고 주민 옆에서 G|작물은 마음을 얻어!|최애가 최고!",
'mail.tip9.from': '미라', 'mail.tip9.sub': '우편함', 'mail.tip9.body': "마을 부탁은 매일 아침|여기로. 부탁 배달하고|금은 네 것.",
'mail.req0.from': '미라', 'mail.req0.sub': '작은 부탁', 'mail.req0.body': "순무 3개 줄래?|브램 스튜 만드는데.|잘 줄게.",
'mail.req1.from': '브램', 'mail.req1.sub': '울타리', 'mail.req1.body': "연못 울타리 무너졌어.|목재 8개 보내줘.",
'mail.req2.from': '주니퍼', 'mail.req2.sub': '빵 주문', 'mail.req2.body': "신선한 달걀 4개 있으면.|아침은 빵 필요|금이 기다려.",
'mail.req3.from': '미라', 'mail.req3.sub': '잼', 'mail.req3.body': "야생 베리 5개 제발.|겨울 잼 만드는데|금과 교환.",
'mail.req4.from': '브램', 'mail.req4.sub': '길', 'mail.req4.body': "마을 길 수리.|돌 8개 보내줘, 마을|감사.",
'mail.req5.from': '주니퍼', 'mail.req5.sub': '수프', 'mail.req5.body': "이번 주 당근 수프.|네 4개로|이익은 네 것.",
'mail.req6.from': '미라', 'mail.req6.sub': '소풍', 'mail.req6.body': "익은 딸기 3개 제발.|연못 소풍|높은 금 줄게.",
'mail.req7.sub': '보석', 'mail.req7.body': "자수정 1개면 여행 상인과|거래. 보내줘 친구!",
'gift.0': '고마워! 원하던 거야.', 'gift.1': '세심하네!', 'gift.2': '착한 마음이네.', 'gift.3': '간직할게. 고마워!',
'mail.ms0.sub': '작은 것', 'mail.ms0.body': "최근 친절했네,|씨앗 남겼어.|심고 기억해!",
'mail.ms1.sub': '고마워', 'mail.ms1.body': "마을에서 고마움.|당근 달고 빨라.|다 팔지 마.",
'mail.ms2.sub': '친구에게', 'mail.ms2.body': "잘 안 말하는데:|썬베일 좋은 친구야.|이 씨앗 받아.",
'mail.ms3.sub': '진심으로', 'mail.ms3.body': "이젠 가족이야.|마을은 네 농장|얘기로 가득. 최고야.",
'mail.welcome.sub': '썬베일 환영', 'mail.welcome.body': "농장에 환영!|우편함은 매일 아침 마을|편지를 모아. 작은|선물로 시작.",
'mail.week.sub': '첫 주', 'mail.week.body': "마을은 널 알아.|부탁 배달하고 금과 우정을.|이웃과 말해.",
'msg.welcome_farm': '썬베일 농장 환영', 'msg.press_h': 'H 도움말', 'msg.welcome_back': '돌아온 걸 환영',
'msg.new_mail': '새 우편 도착', 'msg.save_failed': '저장 실패', 'msg.inv_full': '가득 참',
'msg.rain_waters': '비가 밭을 적셔', 'msg.passed_out': '지쳐 쓰러짐', 'msg.eggs_spoiled': '달걀 상함 - 가득',
'msg.laid': '닭이 {x}개 낳음', 'msg.not_enough_gold': '금 부족', 'msg.coop_full': '우리 가득',
'msg.chicken_joins': '닭 합류!', 'msg.sold_all': '전부 {x}G 판매', 'msg.game_saved': '저장됨',
'msg.too_tired': '너무 tired...', 'msg.not_here': '여기 아님', 'msg.dry_ground': '마른 땅', 'msg.till_first': '먼저 갈기',
'msg.need': '{x} {y} 필요', 'msg.delivered': '배달! +{x}G', 'msg.cluck': '꼬꼬', 'msg.cluck_bang': '꼬꼬!',
'msg.no_one': '근처 아무도 없음', 'msg.hold_gift': '선물 들기', 'msg.not_gift': '선물 아님',
'msg.sound_muted': '음소거', 'msg.sound_on': '소리 켬', 'msg.talked': '+2 우정',
'msg.closer': '{x}와 더 친함', 'msg.day_weather': '{x}일 - {y}',
'tv.0': '내일 날씨...', 'tv.1': '{x} 예상. 계획!', 'tv.2': '프로그램으로 복귀.',
'sign.farm': '썬베일 농장 환영', 'sign.shop': '상점 - 씨앗과 보급',
'map.farm': '썬베일 농장', 'map.house': '네 집', 'map.shop': '잡화점', 'map.hall': '회관', 'map.tavern': '주점',
'gift.line': '멋진 선물! 고마워, 농부.', 'journal': '일지',
'tile.0': '풀', 'tile.1': '풀', 'tile.2': '꽃', 'tile.3': '길', 'tile.4': '물', 'tile.5': '흙', 'tile.6': '젖은 흙',
'tile.7': '바닥', 'tile.8': '벽', 'tile.9': '카펫', 'tile.10': '돌', 'tile.11': '테라스', 'tile.12': '다리', 'tile.13': '모래', 'tile.14': '울타리', 'tile.15': '단단한 나무'
});
