// Sunvale translations: MS SV NO DA FI (part 5b/6)
I18N_ADD('ms', {
'title': 'SUNVALE', 'subtitle': 'LADANG PIKSEL SELESA', 'start': 'MULA LADANG', 'continue': 'TERUSKAN', 'new': 'LADANG BARU',
'controls1': 'WASD JALAN   E BICARA   SPACE ALAT', 'controls2': 'I BEG   H BANTUAN   M MUZIK   ESC REHAT', 'fanmade': 'PERMAINAN LADANG SELESA',
'language': 'BAHASA', 'day': 'HARI', 'mail': 'MEL', 'empty_hands': 'TANGAN KOSONG', 'enter': 'MASUK', 'leave': 'KELUAR', 'sleep': 'TIDUR',
'watch_tv': 'TONTON TV', 'open_chest': 'BUKA PETI', 'read': 'BACA', 'check_mail': 'SEMAK MEL', 'shop': 'KEDAI', 'pet_chicken': 'BELAI AYAM',
'talk_to': 'BERBUAL DENGAN {x}', 'harvest': 'TUAI {x}', 'harvest_generic': 'TUAI', 'check_mail_new': 'SEMAK MEL ({x} BARU)',
'sells_for': 'JUAL {x}G   {y}', 'costs': 'HARGA {x}G   {y}', 'energy_food': '+{x} TENAGA   {y}',
'close': 'TUTUP', 'inventory': 'BEG', 'inventory_chest': 'BEG + PETI', 'chest': 'PETI',
'general_store': 'KEDAI RUNCIT', 'shop_quote': 'JUNIPER: "PILIH SAJA."', 'buy': 'BELI', 'sell': 'JUAL',
'nothing_sell': 'TIADA UNTUK DIJUAL.', 'sell_everything': 'JUAL SEMUA', 'close_esc': 'TUTUP [ESC]',
'mailbox': 'PETI MEL', 'unread': '{x} BELUM BACA', 'caught_up': 'SEMUA DIBACA', 'no_mail': 'TIADA MEL.',
'letters_arrive': 'SURAT TIBA', 'each_morning': 'SETIAP PAGI.', 'letters': '{x} SURAT', 'mailbox_empty': 'PETI KOSONG.',
'village_requests': 'PERMINTAAN KAMPUNG', 'arrive_sleep': 'TIBA SELEPAS TIDUR.', 'from': 'DARI {x}   HARI {y}',
'request_from': 'PERMINTAAN DARI {x}', 'have': 'ADA {x}/{y}', 'reward': 'GANJARAN {x}G', 'delivered': 'DIHANTAR',
'need_more': 'PERLU LAGI', 'deliver': 'HANTAR', 'enclosed_with': 'DARI {x}', 'taken': 'DIAMBIL', 'claim': 'AMBIL',
'nothing_enclosed': '- KOSONG -', 'delete': 'PADAM', 'enter_claims': 'ENTER AMBIL/HANTAR',
'paused': 'REHAT', 'resume': 'TERUSKAN', 'save_game': 'SIMPAN', 'how_to_play': 'CARA MAIN',
'music_on': 'MUZIK: ON', 'music_off': 'MUZIK: OFF', 'quit_title': 'KE TAJUK', 'progress_sleep': 'DISIMPAN SEMASA TIDUR',
'sunny': 'CERAH', 'rain': 'HUJAN', 'storm': 'RIBUT', 'mon': 'ISN', 'tue': 'SEL', 'wed': 'RAB', 'thu': 'KHA', 'fri': 'JUM', 'sat': 'SAB', 'sun': 'AHD',
'best_friends': 'SAHABAT', 'friendship': 'PERSAHABATAN', 'f_full': 'PERSAHABATAN', 'journal': 'JURNAL',
'help.0': 'JALAN       WASD / ANAK PANAH', 'help.1': 'ALAT        SPACE / KLIK', 'help.2': 'BICARA      E', 'help.3': 'HADIAH      G',
'help.4': 'LARI        SHIFT', 'help.5': 'BAR         1-0', 'help.6': 'BEG         I / TAB', 'help.7': 'JURNAL      J',
'help.8': 'MEL         PETI / SAMPUL', 'help.9': 'BISU        M', 'help.10': 'REHAT     ESC', 'help.11': 'TUTUP     ESC',
'tip.0': 'GUNA CANGKUL DI RUMPUT LADANG,', 'tip.1': 'TANAM BENIH, SIRAM SETIAP HARI.', 'tip.2': 'TIDUR DI KATIL UNTUK HARI BARU.',
'tip.3': 'JUAL DI KEDAI.', 'tip.4': 'MAKAN PULIH TENAGA.',
'item.hoe.name': 'Cangkul', 'item.hoe.desc': 'Gembur tanah', 'item.can.name': 'Penyiram', 'item.can.desc': 'Siram tanah',
'item.axe.name': 'Kapak', 'item.axe.desc': 'Tebang pokok', 'item.pick.name': 'Beliung', 'item.pick.desc': 'Pecah batu',
'item.turnip_seeds.name': 'Benih lobak', 'item.turnip_seeds.desc': 'Tumbuh 4 hari', 'item.carrot_seeds.name': 'Benih lobak merah', 'item.carrot_seeds.desc': 'Tumbuh 5 hari',
'item.potato_seeds.name': 'Benih kentang', 'item.potato_seeds.desc': 'Tumbuh 6 hari', 'item.tomato_seeds.name': 'Benih tomato', 'item.tomato_seeds.desc': 'Tumbuh 5 hari',
'item.corn_seeds.name': 'Benih jagung', 'item.corn_seeds.desc': 'Tumbuh 6 hari', 'item.strawberry_seeds.name': 'Benih strawberi', 'item.strawberry_seeds.desc': 'Tumbuh 7 hari',
'item.pumpkin_seeds.name': 'Benih labu', 'item.pumpkin_seeds.desc': 'Tumbuh 9 hari',
'item.turnip.name': 'Lobak', 'item.turnip.desc': 'Rangup pedas', 'item.carrot.name': 'Lobak merah', 'item.carrot.desc': 'Manis rangup',
'item.potato.name': 'Kentang', 'item.potato.desc': 'Ubi padat', 'item.tomato.name': 'Tomato', 'item.tomato.desc': 'Berjus hangat',
'item.corn.name': 'Jagung', 'item.corn.desc': 'Tongkol emas', 'item.strawberry.name': 'Strawberi', 'item.strawberry.desc': 'Beri matahari',
'item.pumpkin.name': 'Labu', 'item.pumpkin.desc': 'Labu gergasi',
'item.veg_stew.name': 'Stew sayur', 'item.veg_stew.desc': 'Akar direbus', 'item.omelette.name': 'Omelet herba', 'item.omelette.desc': 'Telur segar',
'item.berry_pie.name': 'Pai beri', 'item.berry_pie.desc': 'Kulit emas', 'item.pumpkin_soup.name': 'Sup labu', 'item.pumpkin_soup.desc': 'Lembut manis',
'item.wood.name': 'Kayu', 'item.wood.desc': 'Bahan binaan', 'item.stone.name': 'Batu', 'item.stone.desc': 'Bahan binaan',
'item.gem.name': 'Amethyst', 'item.gem.desc': 'Berkilau', 'item.berry.name': 'Beri liar', 'item.berry.desc': 'Dari semak',
'item.egg.name': 'Telur', 'item.egg.desc': 'Segar dari reban', 'item.chicken.name': 'AYAM', 'item.chicken.desc': 'BURUNG MESRA',
'crop.turnip': 'Lobak', 'crop.carrot': 'Lobak merah', 'crop.potato': 'Kentang', 'crop.strawberry': 'Strawberi', 'crop.pumpkin': 'Labu', 'crop.corn': 'Jagung', 'crop.tomato': 'Tomato',
'recipe.veg_stew': 'REBUS AKAR API KECIL', 'recipe.omelette': '2 TELUR DAN HERBA', 'recipe.berry_pie': 'MANIS, AWAS KULIT', 'recipe.pumpkin_soup': 'CUKUP SELEMBAH',
'upgrade.bag': 'BEG BESAR', 'upgrade.bag.d': '50 BUKAN 30', 'upgrade.chest': 'PETI OAK', 'upgrade.chest.d': 'PETI GANDA', 'upgrade.tools': 'ALAT KELULI', 'upgrade.tools.d': 'SETIAP -1',
'npc.mira': 'Mira', 'npc.bram': 'Bram', 'npc.juniper': 'Juniper', 'npc.pip': 'Pip', 'npc.wren': 'Wren', 'npc.sable': 'Sable', 'npc.peony': 'Datuk Peony', 'npc.odin': 'Odin',
'npc.mira.0': "Tanah suka air. Tanaman minum!", 'npc.mira.1': "Tak jual apa, tapi suka ladangmu", 'npc.mira.2': "Hujan bantu percuma. Lihat langit!", 'npc.mira.3': "Labu lambat tapi harga bagus",
'npc.bram.0': "Batu sembunyi amethyst. Bawa beliung!", 'npc.bram.1': "Tidur di kolam. Bantal bagus", 'npc.bram.2': "Tinggalkan tunggul. Tumbuh lagi", 'npc.bram.3': "Awas air dalam selepas pasir",
'npc.juniper.0': "Selamat datang! Benih di rak, telur di poket", 'npc.juniper.1': "Beli murah, tanam tinggi. Itulah rahsia", 'npc.juniper.2': "Ayam bertelur lihat atau tidak",
'mail.tip0.from': 'MIRA', 'mail.tip0.sub': 'BIJAK AIR', 'mail.tip0.body': "Petani baik, tanaman minum baik|semasa tanah lembap malam|Hujan dikira: lihat langit!",
'mail.tip1.from': 'BRAM', 'mail.tip1.sub': 'BATU DAN HARTA', 'mail.tip1.body': "Amethyst di batu pucat|selepas pasir di kolam|Bawa beliung dan tenaga",
'mail.tip2.from': 'JUNIPER', 'mail.tip2.sub': 'HARI PASAR', 'mail.tip2.body': "Kedai bayar penuh semua|yang kau tanam atau gali|Benih tiap hari",
'mail.tip3.from': 'POS SUNVALE', 'mail.tip3.sub': 'RISALAH', 'mail.tip3.body': "AYAM BERTELUR MALAM|BELAI UNTUK PERSAHABATAN|REBAN MUAT ENAM",
'mail.tip4.from': 'MIRA', 'mail.tip4.sub': 'MUSIM LABU', 'mail.tip4.body': "Labu 9 hari tapi|harga gergasi|Tanam awal lupa",
'mail.tip5.from': 'BRAM', 'mail.tip5.sub': 'TUNGGUL', 'mail.tip5.body': "Pokok tinggalkan tunggul|Tunas dalam hari|hutan selalu kembali",
'mail.tip6.from': 'JUNIPER', 'mail.tip6.sub': 'KENYANG', 'mail.tip6.body': "Makan pulih tenaga|Bawa beri di poket|tak pernah pengsan",
'mail.tip7.from': 'POS SUNVALE', 'mail.tip7.sub': 'CUACA', 'mail.tip7.body': "Ribut basahi semua sekali|Cerah keringkan tanah|Siram ikut ramalan",
'mail.tip8.from': 'BRAM', 'mail.tip8.sub': 'KIRIM HADIAH', 'mail.tip8.body': "Pegang barang tekan G dekat|penduduk. Hasil menangkan hati!|Kegemaran menang!",
'mail.tip9.from': 'MIRA', 'mail.tip9.sub': 'TENTANG PETI', 'mail.tip9.body': "Permintaan datang tiap pagi|di sini. Hantar yang mereka|minta, emas milikmu",
'mail.req0.from': 'MIRA', 'mail.req0.sub': 'BANTUAN KECIL', 'mail.req0.body': "3 lobak boleh?|Buat stew untuk Bram|Bayar baik",
'mail.req1.from': 'BRAM', 'mail.req1.sub': 'PAGAR', 'mail.req1.body': "Pagarku di kolam roboh|Hantar 8 kayu, kubaiki",
'mail.req2.from': 'JUNIPER', 'mail.req2.sub': 'TEMPAHAN', 'mail.req2.body': "4 telur segar jika ada|Pagi perlu bakar|emas menunggu",
'mail.req3.from': 'MIRA', 'mail.req3.sub': 'JEM', 'mail.req3.body': "5 beri liar ya|Buat jem musim sejuk|tukar emas",
'mail.req4.from': 'BRAM', 'mail.req4.sub': 'JALAN', 'mail.req4.body': "Jalan perlu baiki|Hantar 8 batu, kampung|berterima kasih",
'mail.req5.from': 'JUNIPER', 'mail.req5.sub': 'SUP', 'mail.req5.body': "Sup lobak minggu ini|4 lobak darimu|untung milikmu",
'mail.req6.from': 'MIRA', 'mail.req6.sub': 'PIKNIK', 'mail.req6.body': "3 strawberi masak ya|Piknik di kolam|bayar emas tinggi",
'mail.req7.sub': 'PERMATA', 'mail.req7.body': "1 amethyst tukar dengan|pedagang. Hantar kawan!",
'gift.0': 'TERIMA KASIH! INI YANG MAHU.', 'gift.1': 'PRIHATIN SEKALI!', 'gift.2': 'HATIMU BAIK.', 'gift.3': 'KUSIMPAN. MAKASIH!',
'mail.ms0.sub': 'HAL KECIL', 'mail.ms0.body': "Kau baik lately|simpan benih|Tanam ingat aku!",
'mail.ms1.sub': 'TERIMA KASIH', 'mail.ms1.body': "Terima kasih dari kampung|Lobak manis|Jangan jual semua",
'mail.ms2.sub': 'UNTUK KAWAN', 'mail.ms2.body': "Jarang cakap:|kau kawan baik Sunvale|Ambil benih ini",
'mail.ms3.sub': 'DARI HATI', 'mail.ms3.body': "Kini keluarga|Kampung bicara tentang|ladangmu. Terbaik di sini",
'mail.welcome.sub': 'SELAMAT DATANG SUNVALE', 'mail.welcome.body': "Selamat datang ladang!|Peti kumpul surat|tiap pagi. Hadiah kecil|mula",
'mail.week.sub': 'MINGGU PERTAMA', 'mail.week.body': "Kampung tahu kamu|Hantar permintaan untuk emas dan sahabat|Bicara jiran",
'msg.welcome_farm': 'SELAMAT DATANG LADANG SUNVALE', 'msg.press_h': 'TEKAN H BANTUAN', 'msg.welcome_back': 'SELAMAT KEMBALI',
'msg.new_mail': 'MEL BARU DATANG', 'msg.save_failed': 'GAGAL SIMPAN', 'msg.inv_full': 'BEG PENUH',
'msg.rain_waters': 'HUJAN MENYIRAM LADANG', 'msg.passed_out': 'PENGSAN KELETIHAN', 'msg.eggs_spoiled': 'TELUR ROSAK - PENUH',
'msg.laid': 'AYAM BERTELUR {x}', 'msg.not_enough_gold': 'EMAS KURANG', 'msg.coop_full': 'REBAN PENUH',
'msg.chicken_joins': 'AYAM SERTAI!', 'msg.sold_all': 'TERJUAL SEMUA {x}G', 'msg.game_saved': 'TERSIMPAN',
'msg.too_tired': 'LETIH...', 'msg.not_here': 'BUKAN DI SINI', 'msg.dry_ground': 'TANAH KERING', 'msg.till_first': 'CANGKUL DULU',
'msg.need': 'PERLU {x} {y}', 'msg.delivered': 'DIHANTAR! +{x}G', 'msg.cluck': 'KOTEK', 'msg.cluck_bang': 'KOTEK!',
'msg.no_one': 'TIADA DEKAT', 'msg.hold_gift': 'PEGANG HADIAH', 'msg.not_gift': 'BUKAN HADIAH',
'msg.sound_muted': 'BISU', 'msg.sound_on': 'BUNYI ON', 'msg.talked': '+2 PERSAHABATAN', 'msg.closer': '{x} LEBIH DEKAT', 'msg.day_weather': 'HARI {x} - {y}',
'tv.0': 'CUACA ESOK...', 'tv.1': 'DIJANGKA {x}. RANCANG!', 'tv.2': 'KEMBALI KE RANCANGAN',
'sign.farm': 'SELAMAT DATANG LADANG SUNVALE', 'sign.shop': 'KEDAI - BENIH DAN LAIN',
'map.farm': 'Ladang Sunvale', 'map.house': 'Rumahmu', 'map.shop': 'Kedai runcit', 'map.hall': 'Dewan bandar', 'map.tavern': 'Kedai minum',
'gift.line': 'Hadiah comel! Makasih, petani',
'tile.0': 'rumput', 'tile.1': 'rumput', 'tile.2': 'bunga', 'tile.3': 'jalan', 'tile.4': 'air', 'tile.5': 'tanah', 'tile.6': 'tanah basah',
'tile.7': 'lantai', 'tile.8': 'dinding', 'tile.9': 'permaidani', 'tile.10': 'batu', 'tile.11': 'teras', 'tile.12': 'jambatan', 'tile.13': 'pasir', 'tile.14': 'pagar', 'tile.15': 'kayu keras'
});
I18N_ADD('sv', {
'title': 'SUNVALE', 'subtitle': 'EN MYSIG PIXELBONDGÅRD', 'start': 'STARTA GÅRDEN', 'continue': 'FORTSÄTT', 'new': 'NY GÅRD',
'controls1': 'WASD GÅ   E PRATA   SPACE VERKTYG', 'controls2': 'I RYGGSÄCK   H HJÄLP   M MUSIK   ESC PAUS', 'fanmade': 'MYSIGT BONDESPEL',
'language': 'SPRÅK', 'day': 'DAG', 'mail': 'POST', 'empty_hands': 'TOMMA HÄNDER', 'enter': 'GÅ IN', 'leave': 'GÅ UT', 'sleep': 'SOV',
'watch_tv': 'TITTA PÅ TV', 'open_chest': 'ÖPPNA KISTA', 'read': 'LÄS', 'check_mail': 'KOLLA POST', 'shop': 'AFFÄR', 'pet_chicken': 'KLAPPA HÖNA',
'talk_to': 'PRATA MED {x}', 'harvest': 'SKÖRDA {x}', 'harvest_generic': 'SKÖRDA', 'check_mail_new': 'KOLLA POST ({x} NY)',
'sells_for': 'SÄLJS FÖR {x}G   {y}', 'costs': 'KOSTAR {x}G   {y}', 'energy_food': '+{x} ENERGI   {y}',
'close': 'STÄNG', 'inventory': 'RYGGSÄCK', 'inventory_chest': 'RYGGSÄCK + KISTA', 'chest': 'KISTA',
'general_store': 'LANTHANDEL', 'shop_quote': 'JUNIPER: "VÄLJ BARA."', 'buy': 'KÖP', 'sell': 'SÄLJ',
'nothing_sell': 'INGET ATT SÄLJA.', 'sell_everything': 'SÄLJ ALLT', 'close_esc': 'STÄNG [ESC]',
'mailbox': 'BREVLÅDA', 'unread': '{x} OLÄST', 'caught_up': 'ALLT LÄST', 'no_mail': 'INGEN POST.',
'letters_arrive': 'BREV KOMMER', 'each_morning': 'VARJE MORGON.', 'letters': '{x} BREV', 'mailbox_empty': 'LÅDAN TOM.',
'village_requests': 'BYNS ÖNSKEMÅL', 'arrive_sleep': 'KOMMER EFTER SÖMN.', 'from': 'FRÅN {x}   DAG {y}',
'request_from': 'ÖNSKEMÅL FRÅN {x}', 'have': 'DU HAR {x}/{y}', 'reward': 'BELÖNING {x}G', 'delivered': 'LEVERERAT',
'need_more': 'BEHÖVER MER', 'deliver': 'LEVERERA', 'enclosed_with': 'BILAGA FRÅN {x}', 'taken': 'TAGEN', 'claim': 'HÄMTA',
'nothing_enclosed': '- INGET MED -', 'delete': 'RADERA', 'enter_claims': 'ENTER HÄMTAR/LEVERERAR',
'paused': 'PAUS', 'resume': 'FORTSÄTT', 'save_game': 'SPARA', 'how_to_play': 'SÅ SPELAR DU',
'music_on': 'MUSIK: PÅ', 'music_off': 'MUSIK: AV', 'quit_title': 'TILL TITEL', 'progress_sleep': 'SPARAS VID SÖMN',
'sunny': 'SOL', 'rain': 'REGN', 'storm': 'STORM', 'mon': 'MÅN', 'tue': 'TIS', 'wed': 'ONS', 'thu': 'TOR', 'fri': 'FRE', 'sat': 'LÖR', 'sun': 'SÖN',
'best_friends': 'BÄSTA VÄNNER', 'friendship': 'VÄNSKAP', 'f_full': 'VÄNSKAP', 'journal': 'DAGBOK',
'help.0': 'GÅ          WASD / PILAR', 'help.1': 'VERKTYG     SPACE / KLICK', 'help.2': 'PRATA       E', 'help.3': 'GÅVA        G',
'help.4': 'SPRING      SHIFT', 'help.5': 'LIST        1-0', 'help.6': 'RYGGSÄCK    I / TAB', 'help.7': 'DAGBOK      J',
'help.8': 'POST        LÅDA / KUVERT', 'help.9': 'LJUDLÖS    M', 'help.10': 'PAUS      ESC', 'help.11': 'STÄNG     ESC',
'tip.0': 'ANVÄND HACKAN PÅ GRÄSET,', 'tip.1': 'PLANTERA FRÖN, VATTNA VARJE DAG.', 'tip.2': 'SOV I SÄNGEN FÖR NY DAG.',
'tip.3': 'SÄLJ I HANDELN.', 'tip.4': 'MAT GER ENERGI.',
'item.hoe.name': 'Hacka', 'item.hoe.desc': 'Luckrar jord', 'item.can.name': 'Vattenkanna', 'item.can.desc': 'Vattnar jord',
'item.axe.name': 'Yxa', 'item.axe.desc': 'Fäller träd', 'item.pick.name': 'Hacka', 'item.pick.desc': 'Krossar sten',
'item.turnip_seeds.name': 'Rovfrön', 'item.turnip_seeds.desc': 'Växer 4 dagar', 'item.carrot_seeds.name': 'Morotsfrön', 'item.carrot_seeds.desc': 'Växer 5 dagar',
'item.potato_seeds.name': 'Potatisfrön', 'item.potato_seeds.desc': 'Växer 6 dagar', 'item.tomato_seeds.name': 'Tomatfrön', 'item.tomato_seeds.desc': 'Växer 5 dagar',
'item.corn_seeds.name': 'Majsfrön', 'item.corn_seeds.desc': 'Växer 6 dagar', 'item.strawberry_seeds.name': 'Jordgubbsfrön', 'item.strawberry_seeds.desc': 'Växer 7 dagar',
'item.pumpkin_seeds.name': 'Pumpafrön', 'item.pumpkin_seeds.desc': 'Växer 9 dagar',
'item.turnip.name': 'Rova', 'item.turnip.desc': 'Krispig het', 'item.carrot.name': 'Morot', 'item.carrot.desc': 'Söt krisp',
'item.potato.name': 'Potatis', 'item.potato.desc': 'Matig knöl', 'item.tomato.name': 'Tomat', 'item.tomato.desc': 'Saftig varm',
'item.corn.name': 'Majs', 'item.corn.desc': 'Gyllene kolv', 'item.strawberry.name': 'Jordgubbe', 'item.strawberry.desc': 'Solvarmt bär',
'item.pumpkin.name': 'Pumpa', 'item.pumpkin.desc': 'En jättepumpa',
'item.veg_stew.name': 'Grönsaksgryta', 'item.veg_stew.desc': 'Sjudna rötter', 'item.omelette.name': 'Örtomelett', 'item.omelette.desc': 'Färska ägg',
'item.berry_pie.name': 'Bärpaj', 'item.berry_pie.desc': 'Gyllene skorpa', 'item.pumpkin_soup.name': 'Pumpasoppa', 'item.pumpkin_soup.desc': 'Len söt',
'item.wood.name': 'Trä', 'item.wood.desc': 'Byggmaterial', 'item.stone.name': 'Sten', 'item.stone.desc': 'Byggmaterial',
'item.gem.name': 'Ametist', 'item.gem.desc': 'Glänser', 'item.berry.name': 'Vildbär', 'item.berry.desc': 'Från buskar',
'item.egg.name': 'Ägg', 'item.egg.desc': 'Färskt från hönshuset', 'item.chicken.name': 'HÖNA', 'item.chicken.desc': 'VÄNLIG FÅGEL',
'crop.turnip': 'Rova', 'crop.carrot': 'Morot', 'crop.potato': 'Potatis', 'crop.strawberry': 'Jordgubbe', 'crop.pumpkin': 'Pumpa', 'crop.corn': 'Majs', 'crop.tomato': 'Tomat',
'recipe.veg_stew': 'SJUD RÖTTER PÅ LÅG VÄRME', 'recipe.omelette': '2 ÄGG OCH ÖRTER', 'recipe.berry_pie': 'SÖT, SE SKORPAN', 'recipe.pumpkin_soup': 'RÄCKER HELA DALEN',
'upgrade.bag': 'STOR RYGGSÄCK', 'upgrade.bag.d': '50 ISTÄLLET 30', 'upgrade.chest': 'EKKISTA', 'upgrade.chest.d': 'DUBBEL KISTA', 'upgrade.tools': 'STÅLVERKTYG', 'upgrade.tools.d': 'VARJE -1',
'npc.mira': 'Mira', 'npc.bram': 'Bram', 'npc.juniper': 'Juniper', 'npc.pip': 'Pip', 'npc.wren': 'Wren', 'npc.sable': 'Sable', 'npc.peony': 'Borgmästare Peony', 'npc.odin': 'Odin',
'npc.mira.0': "Jorden älskar vatten. Grödor dricker!", 'npc.mira.1': "Säljer inget, men älskar din gård", 'npc.mira.2': "Regn hjälper gratis. Titta upp!", 'npc.mira.3': "Pumpor tar tid men bra pris",
'npc.bram.0': "Stenar gömmer ametist. Ta hackan!", 'npc.bram.1': "Sover vid dammen. Bra kudde", 'npc.bram.2': "Lämna stubben. Växer igen", 'npc.bram.3': "Akta djupt vatten efter sand",
'npc.juniper.0': "Välkommen! Frön på hyllan, ägg i fickan", 'npc.juniper.1': "Köp billigt, odla högt. Hela hemligheten", 'npc.juniper.2': "Höns värper vare sig du tittar eller ej",
'mail.tip0.from': 'MIRA', 'mail.tip0.sub': 'VATTENVISDOM', 'mail.tip0.body': "Kära bonde, grödor dricker bäst|när jorden är fuktig på natten|Regn räknas: titta upp!",
'mail.tip1.from': 'BRAM', 'mail.tip1.sub': 'STEN OCH SKATT', 'mail.tip1.body': "Ametist i bleka stenar|efter sand vid dammen|Ta hackan och energi",
'mail.tip2.from': 'JUNIPER', 'mail.tip2.sub': 'MARKNADSDAG', 'mail.tip2.body': "Handeln betalar fullt för allt|du odlar eller gräver|Frön varje dag",
'mail.tip3.from': 'SUNVALE POST', 'mail.tip3.sub': 'BYBLAD', 'mail.tip3.body': "HÖNS VÄRPER ÄGG PÅ NATTEN|KLAPPA DEM FÖR VÄNSKAP|HÖNSHUSET TAR SEX",
'mail.tip4.from': 'MIRA', 'mail.tip4.sub': 'PUMPASÄSONG', 'mail.tip4.body': "Pumpa tar nio dagar men|jättepris|Plantera tidigt glöm",
'mail.tip5.from': 'BRAM', 'mail.tip5.sub': 'STUBBAR', 'mail.tip5.body': "Träd lämnar stubbar|Skott inom dagar|skogen kommer tillbaka",
'mail.tip6.from': 'JUNIPER', 'mail.tip6.sub': 'MÄTT MAGE', 'mail.tip6.body': "Mat ger energi|Ha bär i fickan|svimma aldrig",
'mail.tip7.from': 'SUNVALE POST', 'mail.tip7.sub': 'VÄDER', 'mail.tip7.body': "Storm blöter allt på en gång|Sol torkar jorden|Vattna efter prognos",
'mail.tip8.from': 'BRAM', 'mail.tip8.sub': 'GE GÅVA', 'mail.tip8.body': "Håll föremål tryck G vid|bybo. Skörd vinner hjärtan!|Favorit vinner!",
'mail.tip9.from': 'MIRA', 'mail.tip9.sub': 'OM LÅDAN', 'mail.tip9.body': "Önskemål kommer varje morgon|hit. Leverera vad de|ber om, guldet är ditt",
'mail.req0.from': 'MIRA', 'mail.req0.sub': 'LITEN TJÄNST', 'mail.req0.body': "Tre rovor tack?|Gör gryta åt Bram|Betalar bra",
'mail.req1.from': 'BRAM', 'mail.req1.sub': 'STAKET', 'mail.req1.body': "Mitt staket vid dammen faller|Skicka åtta trä, jag fixar",
'mail.req2.from': 'JUNIPER', 'mail.req2.sub': 'BAKORDER', 'mail.req2.body': "Fyra färska ägg om du har|Morgonen behöver bak|guldet väntar",
'mail.req3.from': 'MIRA', 'mail.req3.sub': 'SYLT', 'mail.req3.body': "Fem vildbär tack|Gör sylt till vintern|byter mot guld",
'mail.req4.from': 'BRAM', 'mail.req4.sub': 'VÄG', 'mail.req4.body': "Vägen behöver lagas|Skicka åtta sten, byn|tackar",
'mail.req5.from': 'JUNIPER', 'mail.req5.sub': 'SOPPA', 'mail.req5.body': "Morotssoppa denna vecka|Fyra morötter från dig|vinsten din",
'mail.req6.from': 'MIRA', 'mail.req6.sub': 'PICKNICK', 'mail.req6.body': "Tre mogna jordgubbar tack|Picknick vid dammen|betalar toppguld",
'mail.req7.sub': 'JUvel', 'mail.req7.body': "En ametist handlar med|resande. Skicka vän!",
'gift.0': 'TACK! PRECIS VAD JAG VILLE.', 'gift.1': 'VAD OMTÄNKSAMT!', 'gift.2': 'DU HAR GOTT HJÄRTA.', 'gift.3': 'JAG SPARAR DET. TACK!',
'mail.ms0.sub': 'LITET', 'mail.ms0.body': "Du var snäll lately|sparade frön|Plantera minns mig!",
'mail.ms1.sub': 'TACK', 'mail.ms1.body': "Tack från byn|Morötter söta| Sälj inte alla",
'mail.ms2.sub': 'TILL VÄN', 'mail.ms2.body': "Säger sällan:|du är god vän till Sunvale|Ta dessa frön",
'mail.ms3.sub': 'FRÅN HJÄRTAT', 'mail.ms3.body': "Nu familj|Byn pratar om|din gård. Bäst här",
'mail.welcome.sub': 'VÄLKOMMEN TILL SUNVALE', 'mail.welcome.body': "Välkommen till gården!|Lådan samlar post|varje morgon. Liten present|börja",
'mail.week.sub': 'FÖRSTA VECKAN', 'mail.week.body': "Byn känner dig|Leverera önskemål för guld och vänskap|Prata med grannar",
'msg.welcome_farm': 'VÄLKOMMEN TILL SUNVALE-GÅRDEN', 'msg.press_h': 'TRYCK H FÖR HJÄLP', 'msg.welcome_back': 'VÄLKOMMEN TILLBAKA',
'msg.new_mail': 'NY POST KOM', 'msg.save_failed': 'SPARA MISSLYCKADES', 'msg.inv_full': 'RYGGSÄCK FULL',
'msg.rain_waters': 'REGN VATTNAR FÄLTEN', 'msg.passed_out': 'SVIMMADE AV TRÖTTHET', 'msg.eggs_spoiled': 'ÄGG FÖRSTÖRDA - FULLT',
'msg.laid': 'HÖNS VÄRPTE {x} ÄGG', 'msg.not_enough_gold': 'INTE TILLRÄCKLIGT GULD', 'msg.coop_full': 'HÖNSHUS FULLT',
'msg.chicken_joins': 'EN HÖNA GÅR MED!', 'msg.sold_all': 'SÅLDE ALLT FÖR {x}G', 'msg.game_saved': 'SPARAT',
'msg.too_tired': 'TRÖTT...', 'msg.not_here': 'INTE HÄR', 'msg.dry_ground': 'TORR JORD', 'msg.till_first': 'HACKA FÖRST',
'msg.need': 'BEHÖVER {x} {y}', 'msg.delivered': 'LEVERERAT! +{x}G', 'msg.cluck': 'KACKEL', 'msg.cluck_bang': 'KACKEL!',
'msg.no_one': 'INGEN NÄRA', 'msg.hold_gift': 'HÅLL GÅVA', 'msg.not_gift': 'INGEN GÅVA',
'msg.sound_muted': 'LJUD AV', 'msg.sound_on': 'LJUD PÅ', 'msg.talked': '+2 VÄNSKAP', 'msg.closer': '{x} NÄRMARE VÄN', 'msg.day_weather': 'DAG {x} - {y}',
'tv.0': 'VÄDER IMORGON...', 'tv.1': 'VÄNTAS {x}. PLANERA!', 'tv.2': 'TILLBAKA TILL PROGRAMMET',
'sign.farm': 'VÄLKOMMEN TILL SUNVALE-GÅRDEN', 'sign.shop': 'AFFÄR - FRÖN OCH MER',
'map.farm': 'Sunvale-gården', 'map.house': 'Ditt hus', 'map.shop': 'Lanthandel', 'map.hall': 'Rådhuset', 'map.tavern': 'Krogen',
'gift.line': 'Vilken fin present! Tack, bonde',
'tile.0': 'gräs', 'tile.1': 'gräs', 'tile.2': 'blommor', 'tile.3': 'stig', 'tile.4': 'vatten', 'tile.5': 'jord', 'tile.6': 'våt jord',
'tile.7': 'golv', 'tile.8': 'vägg', 'tile.9': 'matta', 'tile.10': 'sten', 'tile.11': 'terrass', 'tile.12': 'bro', 'tile.13': 'sand', 'tile.14': 'staket', 'tile.15': 'hårt trä'
});
